"use client";

import { useEffect, useState } from "react";
import { SUB_TEAMS } from "@/lib/subteams";

type User = { _id: string; name: string; email: string; studentId: string; mobile: string; subTeam: string; position: string; role: string; status: string; profilePicUrl?: string };
const statuses = ["pending", "approved", "rejected"];

export function AdminDashboard() {
  const [users, setUsers] = useState<User[]>([]); const [filter, setFilter] = useState("pending"); const [notice, setNotice] = useState(""); const [loading, setLoading] = useState(true);
  const load = async () => { setLoading(true); const res = await fetch(`/api/admin/users?status=${filter}`); const data = await res.json(); setUsers(data.users ?? []); setNotice(res.ok ? "" : data.error); setLoading(false); };
  useEffect(() => { let cancelled = false; fetch(`/api/admin/users?status=`).then(async (res) => ({ res, data: await res.json() })).then(({ res, data }) => { if (!cancelled) { setUsers(data.users ?? []); setNotice(res.ok ? "" : data.error); setLoading(false); } }).catch(() => { if (!cancelled) { setNotice("Unable to load members."); setLoading(false); } }); return () => { cancelled = true; }; }, [filter]);
  async function patch(id: string, update: Record<string, string>) { const res = await fetch(`/api/admin/users/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(update) }); const data = await res.json(); setNotice(data.message || data.error || "Member updated."); if (res.ok) load(); }
  async function remove(id: string) { if (!window.confirm("Remove this member and delete their ImageKit profile image?")) return; const res = await fetch(`/api/admin/users/${id}`, { method: "DELETE" }); const data = await res.json(); setNotice(data.message || data.error); if (res.ok) load(); }
  return <div><div className="flex flex-wrap gap-2 border-b border-slate-700 pb-5">{statuses.map((status) => <button key={status} onClick={() => setFilter(status)} className={`border px-4 py-2 font-mono text-xs uppercase tracking-wider ${filter === status ? "border-cyan-400 bg-cyan-400/10 text-cyan-200" : "border-slate-700 text-slate-400 hover:text-white"}`}>{status}</button>)}</div>{notice && <p className="mt-5 border border-cyan-400/30 bg-cyan-950/20 p-3 text-sm text-cyan-100">{notice}</p>}{loading ? <p className="mt-8 font-mono text-xs uppercase tracking-widest text-slate-500">Loading roster…</p> : users.length === 0 ? <p className="mt-8 text-sm text-slate-500">No {filter} registrations.</p> : <div className="mt-6 overflow-x-auto border border-slate-700"><table className="w-full min-w-[840px] text-left text-sm"><thead className="bg-slate-950 font-mono text-[10px] uppercase tracking-widest text-slate-500"><tr><th className="p-3">Member</th><th className="p-3">Sub-team / position</th><th className="p-3">Role</th><th className="p-3">Actions</th></tr></thead><tbody>{users.map((user) => <tr key={user._id} className="border-t border-slate-800 align-top"><td className="p-3"><div className="flex gap-3">{user.profilePicUrl ? <img src={user.profilePicUrl} alt="" className="h-10 w-10 object-cover" /> : null}<div><p className="font-semibold text-slate-100">{user.name}</p><p className="text-xs text-slate-500">{user.email} · {user.studentId}</p><p className="text-xs text-slate-500">{user.mobile}</p></div></div></td><td className="p-3"><select value={user.subTeam} onChange={(e) => patch(user._id, { subTeam: e.target.value })} className="border border-slate-700 bg-slate-950 p-1.5 text-xs">{SUB_TEAMS.map((team) => <option key={team}>{team}</option>)}</select><input value={user.position} onChange={(e) => setUsers((all) => all.map((item) => item._id === user._id ? { ...item, position: e.target.value } : item))} onBlur={(e) => patch(user._id, { position: e.target.value })} className="mt-2 block border border-slate-700 bg-slate-950 p-1.5 text-xs" /></td><td className="p-3"><select value={user.role} onChange={(e) => patch(user._id, { role: e.target.value })} className="border border-slate-700 bg-slate-950 p-1.5 text-xs"><option>member</option><option>lead</option><option>admin</option></select></td><td className="space-x-2 p-3">{user.status === "pending" && <><button onClick={() => patch(user._id, { status: "approved" })} className="border border-emerald-500/60 px-2 py-1 text-xs text-emerald-300 hover:bg-emerald-950">Approve</button><button onClick={() => patch(user._id, { status: "rejected" })} className="border border-red-500/60 px-2 py-1 text-xs text-red-300 hover:bg-red-950">Reject</button></>}<button onClick={() => remove(user._id)} className="border border-red-500/60 px-2 py-1 text-xs text-red-300 hover:bg-red-950">Remove</button></td></tr>)}</tbody></table></div>}</div>;
}
