"use client";

import { useState, type FormEvent } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { MEMBER_TYPES, POSITIONS } from "@/lib/member-options";
import { SUB_TEAMS } from "@/lib/subteams";

const field = "mt-1 w-full border border-slate-700 bg-black/25 px-3 py-2.5 text-sm text-slate-100 outline-none transition placeholder:text-slate-600 focus:border-cyan-400";

export function RegisterForm() {
  const [message, setMessage] = useState(""); const [pending, setPending] = useState(false); const [done, setDone] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const formData = new FormData(form); if (formData.get("password") !== formData.get("confirmPassword")) return setMessage("Passwords do not match."); setPending(true); setMessage(""); const response = await fetch("/api/auth/register", { method: "POST", body: formData }); const data = await response.json(); setPending(false); setMessage(data.message || data.error); setDone(response.ok); }
  if (done) return <div className="border border-cyan-400/40 bg-cyan-950/20 p-7"><p className="font-orbitron text-lg text-cyan-200">Transmission received.</p><p className="mt-3 text-sm leading-6 text-slate-300">{message}</p><Link href="/login" className="mt-6 inline-block font-mono text-xs uppercase tracking-widest text-cyan-300 hover:text-white">Proceed to sign in →</Link></div>;
  return <form onSubmit={submit} className="grid gap-4 sm:grid-cols-2">{message && <p className="sm:col-span-2 border border-red-500/40 bg-red-950/30 p-3 text-sm text-red-200">{message}</p>}<Field label="Full name" name="name" required /><Field label="Student ID" name="studentId" required /><Field label="University email" name="email" type="email" required /><Field label="Mobile number" name="mobile" type="tel" required /><label className="sm:col-span-2 text-xs font-semibold uppercase tracking-wider text-slate-400">Profile picture<input name="profilePicture" type="file" accept="image/jpeg,image/png,image/webp" required className={`${field} file:mr-3 file:border-0 file:bg-cyan-400/10 file:px-2 file:py-1 file:text-xs file:text-cyan-200`} /><span className="mt-1 block text-[11px] text-slate-500">JPG, PNG, or WebP · maximum 2 MB</span></label><label className="text-xs font-semibold uppercase tracking-wider text-slate-400">Membership<select name="memberType" required defaultValue="" className={field}><option value="" disabled>Choose one</option>{MEMBER_TYPES.map((type) => <option key={type}>{type}</option>)}</select></label><label className="text-xs font-semibold uppercase tracking-wider text-slate-400">Sub-team<select name="subTeam" required defaultValue="" className={field}><option value="" disabled>Select your team</option>{SUB_TEAMS.map((team) => <option key={team}>{team}</option>)}</select></label><label className="text-xs font-semibold uppercase tracking-wider text-slate-400">Position<select name="position" required defaultValue="Member" className={field}>{POSITIONS.map((position) => <option key={position}>{position}</option>)}</select></label><Field label="LinkedIn URL (optional)" name="linkedin" type="url" /><Field label="Password" name="password" type="password" minLength={8} required /><Field label="Confirm password" name="confirmPassword" type="password" minLength={8} required /><button disabled={pending} className="sm:col-span-2 mt-2 border border-cyan-400 bg-cyan-400 px-5 py-3 font-orbitron text-xs font-bold uppercase tracking-widest text-slate-950 transition hover:bg-white disabled:opacity-60">{pending ? "Sending…" : "Submit registration"}</button><p className="sm:col-span-2 text-center text-sm text-slate-500">Already registered? <Link href="/login" className="text-cyan-300 hover:text-white">Sign in</Link></p></form>;
}

export function LoginForm() { const router = useRouter(); const [message, setMessage] = useState(""); const [pending, setPending] = useState(false); async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); setMessage(""); const form = new FormData(event.currentTarget); const response = await fetch("/api/auth/login", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email: form.get("email"), password: form.get("password") }) }); const data = await response.json(); setPending(false); if (!response.ok) return setMessage(data.error); router.push(data.user.role === "admin" ? "/admin" : "/team"); router.refresh(); } return <form onSubmit={submit} className="space-y-4">{message && <p className="border border-red-500/40 bg-red-950/30 p-3 text-sm text-red-200">{message}</p>}<Field label="Email" name="email" type="email" required /><Field label="Password" name="password" type="password" required /><button disabled={pending} className="mt-2 w-full border border-cyan-400 bg-cyan-400 px-5 py-3 font-orbitron text-xs font-bold uppercase tracking-widest text-slate-950 transition hover:bg-white disabled:opacity-60">{pending ? "Verifying…" : "Sign in"}</button><p className="text-center text-sm text-slate-500">New to ROSB? <Link href="/register" className="text-cyan-300 hover:text-white">Register</Link></p></form>; }

function Field({ label, className = "", ...props }: React.ComponentProps<"input"> & { label: string }) { return <label className={`${className} block text-xs font-semibold uppercase tracking-wider text-slate-400`}>{label}<input {...props} className={field} /></label>; }
